config/routes.rb
Rails.application.routes.draw do
  get 'readers/new'
  get 'readers/create'
  get '/books', to: 'books#index'
  get '/home' , to: 'pages#home'
  devise_for :users
root 'pages#home'
  resources :books do
    resources :chapters
    resources :readers, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user 
    has_many :chapters, dependent: :destroy
    has_and_belongs_to_many :readers

    validates :title, presence: true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :book
end

app/models/reader.rb
class Reader < ApplicationRecord
    has_and_belongs_to_many :books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books or /books.json
  def create
      @book = current_user.books.build(book_params)

      respond_to do |format|
        if @book.save
          format.html { redirect_to book_url(@book), notice: "Tv show was successfully created." }
          format.json { render :show, status: :created, location: @book }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    end
   
  

  # PATCH/PUT /books/1 or /books/1.json
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    book = Book.find(params[:id])
    book.destroy

    flash[:notice] = "El libro ha sido eliminado exitosamente"
    redirect_to books_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :description, :image_url, :publication_date, :price)
    end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
    def create
        @book = Book.find(params[:book_id])
        @chapter = @book.chapters.create(chapter_params)
        redirect_to book_path(@book)
    end

    private
    def chapter_params
        params.require(:chapter).permit(:chapter_number, :title, :summary)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  def new
    @book = Book.find(params[:book_id])
    @reader = @book.readers.build
  end

  def create
    @book = Book.find(params[:book_id])
    @reader = @book.readers.create!(reader_params)
    redirect_to @book
  end

  private

  def reader_params
      params.require(:reader).permit(:first_name, :last_name, :age, :comment)
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :publication_date %>
    <%= form.date_select :publication_date %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editar Libro</h1>
<%= form_for @book do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>
  <div>
    <%= f.label :publication_date %>
    <%= f.date_field :publication_date %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.number_field :price, step: :any %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div>
    <nav class="navbar navbar-expand-sm bg-secondary navbar-light">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'Home', home_path, class: 'btn btn-dark'%>
        </li>
        <li class="nav-item">  
          <% if user_signed_in? %>
          <%= link_to 'Ingresar Nuevo Libro', new_book_path, class: 'btn btn-info'%>
          <% end %>
        </li>
      </ul>
    </nav>  
  </div>
  <div class="row">
    <div class="col-12"> 
<br>
<h1>Libros</h1>

<div class="table-responsive-lg">
<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Título</th>
      <th>Autor</th>
      <th>Descripción</th>
      <th>Imagen url</th>
      <th>Fecha de Publicación</th>
      <th>Precio Promedio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><b><%= book.title %></b></td>
        <td><%= book.author %></td>
        <td><%= book.description %></td>
        <td><%= book.image_url %></td>
        <td><%= book.publication_date %></td>
        <td><%= book.price %></td>

        <% if user_signed_in? %>
        <td><%= link_to 'Ver', book, class: 'btn btn-outline-success' %></td>
        <% end %>
        <% if (user_signed_in? && (current_user == book.user)) %>
            <td><%= link_to 'Editar', edit_book_path(book), class: 'btn btn-outline-warning' %></td>
            <td><%= link_to 'Eliminar', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger'%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br><br>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<br><br>
<nav class="navbar navbar-expand-sm bg-secondary navbar-light">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'Home', home_path, class: 'btn btn-secondary'%>
        </li>
      </ul>
</nav>
<div class="container">

<div class="row">
  <div class="col-6">
  
<br>
<h1>Nuevo Libro</h1>
<%= form_with model: Book.new do |f| %>

  <div class="form-check" >
    <%= f.label :title, "Título" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <br>
  <div class="form-check" >
    <%= f.label :author, "Autor" %>
    <%= f.text_field :author, class: 'form-control' %>
  </div>
  <br>
  <div class="form-check" >
    <%= f.label :description, "Descripción" %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <br>
  <div class="form-check" >
    <%= f.label :image_url, "Imagen" %>
    <%= f.text_field :image_url, class: 'form-control' %>
  </div>
  <br>
  <div class="form-check" >
    <%= f.label :publication_date, "Fecha_publicación" %>
    <%= f.date_field :publication_date, class: 'form-control' %>
  </div>
  <br>
  <div class="form-check" >
    <%= f.label :price, "Precio" %>
    <%= f.number_field :price, step: :any, class: 'form-control' %>
  </div>
<br>
  <div class="form-check" >
    <%= f.submit "Crear libro", class: "btn btn-info mt-3" %>
  </div>
  <br>
<% end %>
</div>
  </div>
  </div>

app/views/books/show.html.erb
<br><br>
<div class="container">
  <div class="row">
    <div class="col-12">
        <div>
            <nav class="navbar navbar-expand-sm bg-dark navbar-light">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <%= link_to 'Home', home_path, class: 'btn btn-secondary'%>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Editar', edit_book_path(@book), class: "btn btn-info" %>
                    </li>
                </ul>
            </nav> 
        </div>
<br>
<h1>DETALLES DEL LIBRO</h1>
<hr>
<img style="width: 200px;" src="<%=@book.image_url%>" />
<br><br>
<P>
<strong>Nombre:</strong>
<%= @book.title %>
</p>

<p>
<strong>Autor:</strong>
<%= @book.author %>
</p>

<p>
<strong>Descripción:</strong>
<%= @book.description %>
</p>


<p>
<strong>Fecha de publicación:</strong>
<%= @book.publication_date %>
</p>

<p>
<strong>Precio promedio:</strong>
<%= @book.price %>
</p>
<br>
<hr>
<h4>Lectores:</h4>

    <div>
        <% if @book.readers %>
        <% @book.readers.each do |reader|%>
        <strong><%= reader.id %>: 
        <p><b>Nombre:</b>  </strong><%= "#{reader.first_name} #{reader.last_name}" %>
        <br>
        <p><b>Comentario:</b>  </strong><%="#{reader.comment}"%></p>
        <% end %>
    </div>
    <% else %>
        <% 'No Readers Added!!!'%>
    <% end %>
<br>
<%= link_to 'Agregar Lectores', new_book_reader_path(@book) %>
<br><br>
<hr>
<h2>Listado de Capítulos:</h2>
<% @book.chapters.each do |chapter| %>
    <p>
        <strong>Capítulo número:</strong>
        <%= chapter.chapter_number %>
    </p>

    <p>
        <strong>Título:</strong>
        <%= chapter.title %>
    </p>

    <p>
        <strong>Resumen:</strong>
        <%= chapter.summary%>
    </p>
<% end %>
<br>
<br>

<hr>
<h3>Agregue un capítulo:</h3>
<%= form_with model: [ @book, @book.chapters.build ] do |form| %>
    <p>
        <%= form.label :capítulo_número %><br>
        <%= form.number_field :chapter_number %>
    </p>
    <p>
        <%= form.label :título %><br>
        <%= form.text_field :title %>
    </p>
    <p>
        <%= form.label :resumen %><br>
        <%= form.text_area :summary %>
    </p>
    <p>
        <%= form.submit "Crear capítulo"%>
    </p>
<% end %>
<br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksCatalogo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body style="background-color:OldLace;">
  <br><br>

  <div class="container">
    <div class="row">
      <div class="col-12">
        
        <div class="col-12">
        <% if user_signed_in? %>
            <p><b>Bienvenido: <%= current_user.email %>!!</b></p>
            <%= link_to "Salir", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
        
          <div class="text-right"><%= link_to 'Ir a Tabla Catálogo', books_path, class: 'btn btn-info' %></div>
        </div>
        <% else %>
          <div>
            <nav class="navbar navbar-expand-sm bg-dark navbar-light">
            <ul class="navbar-nav">
              <li class="nav-item active">
              <%= link_to 'Home', home_path, class: 'btn btn-secondary'%>
              </li>
              <li class="nav-item">
                <%= link_to "Registrarse", new_user_registration_path, class: 'btn btn-dark' %>
              </li>
              <li class="nav-item">  
                <%= link_to "Ingresar", new_user_session_path, class: 'btn btn-dark' %>
              </li>
            </ul>
            </nav> 
          </div>
        </div> 
        <% end %>
      <%= yield %>
      </div>
    </div>
</div>

  </body>
</html>

app/views/pages/home.html.erb
<br>
<div class="container">
    <div class="row">
        <div class="col-12">
            <hr>
            <h1 class="display-2 text-success">Catálogo de Libros</h1>
            <h2>Bienvenidos!!!</h2>
            <hr>
            <%= image_tag('libros.jpg', size: "1120x300", alt: "Libros", class: 'rounded', class: 'mx-auto d-block', class: 'img-fluid')%>
            <br>
            <hr>
        </div>
        <br>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="media">
            <div class="media-body">
                <h5 class="display-4 text-success">Nuestro Catálogo</h5>
                <p class="lead text-secondary">En este catálago podrás encontrar una lista con los libros más vendidos en el mundo, donde conocerás el nombre de sus autores, un pequeño resumen de los libros, su fecha de publicación y un precio de venta estimado de éstos.<br>
                    Adicionalmente, con solo registrarte, puedes colaborarnos adicionando nuevos títulos a nuestro catálogo para hacerlo aún más completo y nutrido.<br><br> Te esperamos!!</p>
                <hr>
            </div>
        </div>
    </div>
</div>
<br>
<br>

app/views/readers/create.html.erb
<h1>Readers#create</h1>
<p>Find me in app/views/readers/create.html.erb</p>

app/views/readers/new.html.erb
<div class="container">
    <div class="row">
      <div class="col-10">
<h1>Agregar Lectores a Libros</h1>

<%= form_with(model:[@book, @reader]) do |form| %>
    <div class="field">
        <%= form.label :nombre %>
        <%= form.text_field :first_name %>
    </div>
<br>
    <div class="field">
        <%= form.label :apellido %>
        <%= form.text_field :last_name %>
    </div>
<br>
    <div class="field">
        <%= form.label :edad %>
        <%= form.number_field :age %>
    </div>
<br>
    <div class="field">
        <%= form.label :comentario %>
        <%= form.text_field :comment %>
    </div>
    <br>
    <div class="field">
        <%= form.submit "Crear Lector", class: 'btn btn-info mt-3'%>
    </div>
<% end %>
</div>
</div>
</div>
<br><br>